import { Sidebar } from "flowbite-react";
import Head from "next/head";
import React from "react";
import { DashboardNavbar, DefaultNavbar } from "./navbar";
import { ArrowUturnRightIcon, BookOpenIcon, HomeIcon, HomeModernIcon, InformationCircleIcon, UsersIcon } from "@heroicons/react/24/solid"

const DefaultLayout = ({ children, title, setParentState }: { children: React.ReactNode, title: string, setParentState: (state: string) => void }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto px-5">
                <DefaultNavbar setParentState={setParentState} />
                {children}
            </main>

            {/* <Footer /> */}
        </>
    )
}

const DashboardLayout = ({ children, title, setParentState }: { children: React.ReactNode, title: string, setParentState: (state: string) => void }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="px-5 w-[100vw]">
                <div className="flex flex-row w-full">
                    <div className="flex-none">
                        <Sidebar aria-label="Sidebar with content separator example">
                            <Sidebar.Items>
                                <Sidebar.ItemGroup>
                                    {/* <Sidebar.Logo href="/dashboard" img="https://flowbite.com/docs/images/logo.svg"> ThingsToday </Sidebar.Logo>
                                    <Sidebar.Item href="/dashboard" icon={HomeIcon} > */}
                                    <Sidebar.Logo href="" onClick={() => setParentState("")} img="https://flowbite.com/docs/images/logo.svg"> ThingsToday </Sidebar.Logo>
                                    <div onClick={() => setParentState("")}>
                                        <Sidebar.Item icon={HomeIcon} >
                                            Home
                                        </Sidebar.Item>
                                    </div>
                                    <div onClick={() => setParentState("books")}>
                                        <Sidebar.Item icon={BookOpenIcon} >
                                            Books
                                        </Sidebar.Item>
                                    </div>
                                    <Sidebar.Item href="#" icon={HomeModernIcon} >
                                        Faculty
                                    </Sidebar.Item>
                                    <Sidebar.Item href="#" icon={UsersIcon} >
                                        Account
                                    </Sidebar.Item>
                                </Sidebar.ItemGroup>
                                <Sidebar.ItemGroup>
                                    <div onClick={() => setParentState("help")}>
                                        <Sidebar.Item href="#" icon={InformationCircleIcon} >
                                            Help
                                        </Sidebar.Item>
                                    </div>
                                    <Sidebar.Item href="#" icon={ArrowUturnRightIcon} >
                                        Logout
                                    </Sidebar.Item>
                                </Sidebar.ItemGroup>
                            </Sidebar.Items>
                        </Sidebar>
                    </div>
                    <div className="flex-auto">
                        <DashboardNavbar />
                        {children}
                    </div>
                </div>
            </main>

            {/* <Footer /> */}
        </>
    )
}

export { DefaultLayout, DashboardLayout }